//Program to generate 'n' Fibonacci numbers by use of static variables in a function as well as using recursion
#include<stdio.h>

int fibonacci_recurse(int n)
{
	int temp=2;
	if((n==1)||(n==2))
		return 1;
	else
	{
		if(n==3)
			return temp;
		else 	
		return temp+fibonacci_recurse(n-1);
	}

}
int fibonacci_stat(int n)
{
	int n1=1, n2=1, temp;
	static int next,prev;
	if((n==1)||(n==2))
		return 1;
	else
	{
		if(n=3)
			prev=n2+n1;
		next=next+prev;
		prev=next;
		return next;
	}



}
void main()
{
	int i,n;
	do
	{
	printf("Enter how many numbers of Fibonacci sequence is to be printed\n");
	scanf("%d", &n);
	if(n<1)
		printf("Please enter a positive number greater than or equal to 1\n");
	}
	while(n<1);

	printf("The following sequence is generated by using static variables in function\n");
	for(i=1;i<=n;i++)
		printf("%d\t", fibonacci_stat(i));
	printf("\n");

	printf("The following sequence is generated by using recursion\n");
	for(i=1;i<=n;i++)
		printf("%d\t", fibonacci_recurse(i));
	printf("\n");

}

